### ISSUE TITLE
Validation error in Parameters for Task type Pass

### ISSUE THREAD

**Issue by soumil-tempus** [ChristopheBougere/asl-validator#101]
**Describe the bug**
For State Type Pass it throws validation errror
```
 keyword: 'type',
    dataPath: ".States['EmptyState'].Parameters[0]",
    schemaPath: 'pass.json#/properties/Parameters/items/type',
    params: { type: 'object' },
    message: 'should be object'
```
**To Reproduce**
Please provide a complete state machine definition:
```json
{
  "StartAt": "EmptyState",
  "States": {
    "EmptyState": {
       "Type": "Pass",
      "Parameters": ["abc"],
      "ResultPath": "$.emptyState",
      "End": true
    }
  }
}
```

**Expected behavior**

Parameters can accept ARRAY, NUMBER, BOOLEAN, OBJECT, STRING

**Version:** [e.g. 1.9.4, can be found by running `asl-validator --version`]
2.2.1
**Additional context**

**Comment by ChristopheBougere** [comment]
Released in 3.0.1
