### ISSUE TITLE
Error in asl inspection in test case

### ISSUE THREAD

**Issue by fhyoga** [ChristopheBougere/asl-validator#114]
**Describe the bug**
Error in asl inspection in test case
{
    'Error code': 'SCHEMA_VALIDATION_FAILED',
    Message: '/States/X is invalid. must match exactly one schema in oneOf',
    schemaError: { instancePath: '/States/X', schemaPath: '#/oneOf' }
  }
**To Reproduce**
Please provide a complete state machine definition:
```json
{
  "Comment": "https://states-language.net/spec.html#parameters",
  "StartAt": "X",
  "States": {
    "X": {
      "Type": "Task",
      "Resource": "arn:aws:swf:us-east-1:123456789012:task:X",
      "Parameters": {
        "flagged": true,
        "parts": {
          "first.$": "$.vals[0]",
          "last3.$": "$.vals[3:]"
        }
      },
      "End": true
    }
  }
}
```

**Expected behavior**

**Version:**
3.0.8
**Additional context**

**Comment by massfords** [comment]
@fhyoga 

I just pushed a branch with your example as a test and it passes without any errors.

https://github.com/ChristopheBougere/asl-validator/tree/issue114

Can you confirm that you are using the latest version?

**Comment by ChristopheBougere** [comment]
Closing as it seems to work. @fhyoga feel free to reopen if you have more details.
