### ISSUE TITLE
Add support for new Distributed Map in Step Functions Definition

### ISSUE THREAD

**Issue by harazdovskiy** [ChristopheBougere/asl-validator#115]
**Is your feature request related to a problem? Please describe.**
Wide known [serverless-step-functions](https://github.com/serverless-operations/serverless-step-functions) module depends on asl in [this](https://github.com/serverless-operations/serverless-step-functions/blob/master/lib/deploy/stepFunctions/compileStateMachines.js#L121) place. As @brycenrogers mentioned [here](https://github.com/serverless-operations/serverless-step-functions/pull/539) 

> Note: this does not currently work with validate: true as [asl-validator](https://github.com/ChristopheBougere/asl-validator) does not yet support this behavior.

I've recently faced a limitation in step function, found out it can be fixed with new functionality however syntax validator (asl-validator) does not support it(

We kindly ask to extend the asl-validator with support of new [DISTRIBUTED](https://docs.aws.amazon.com/step-functions/latest/dg/concepts-asl-use-map-state-distributed.html#distributed-map-execution-details) Map options
<img width="295" alt="Screenshot 2023-01-05 at 01 40 48" src="https://user-images.githubusercontent.com/19535641/210670514-ca79886b-9ed7-484f-ad9b-b7e3bb6e1ee1.png">

**Describe the solution you'd like**
I guess [this](https://github.com/ChristopheBougere/asl-validator/blob/master/src/schemas/map.json) file should be updated with new properties that Map supports.
Then I will initiate the serverless-step-functions module to update asl-validate -> now we can deploy step functions with fresh AWS functionality altogether) 

**Describe alternatives you've considered**
Don't think we can avoid updating the asl-validator with new AWS functionality

**Additional context**
https://docs.aws.amazon.com/step-functions/latest/dg/concepts-inline-vs-distributed-map.html

**Comment by ChristopheBougere** [comment]
@harazdovskiy #116 has been released in v3.1.0, could you give it a try?

**Comment by harazdovskiy** [comment]
Big thanks to you guys @massfords, @ChristopheBougere! Tested new asl-validator with latest changes of sls-step function. All tests passed

Before:
<img width="2055" alt="Screenshot 2023-01-14 at 21 15 47" src="https://user-images.githubusercontent.com/19535641/212492216-365b3133-12c5-401d-b104-e169f00fc845.png">

With new version
<img width="2055" alt="Screenshot 2023-01-14 at 21 16 50" src="https://user-images.githubusercontent.com/19535641/212492279-469b173b-c1db-41bb-b63d-393aa25586ec.png">
