### ISSUE TITLE
Add YAML support

### ISSUE THREAD

**Issue by davidjb** [ChristopheBougere/asl-validator#136]
**Is your feature request related to a problem? Please describe.**
ASL written in YAML is supported natively by various AWS tools (https://docs.aws.amazon.com/step-functions/latest/dg/development-options.html#development-options-format) and makes ASL significantly easier to read, write and annotate - YAML supports inline comments, multiline strings, amongst other features.

**Describe the solution you'd like**
The ASL validator tool to be able to validate `.yaml`/`.yml` files natively, ideally automatically loading the file based upon its type (e.g. `asl-validator statemachine/foo.asl.yml`).

**Describe alternatives you've considered**
I'm currently converting my YAML into JSON dynamically and passing it through at the shell level, like so:
```sh
asl-validator --json-definition "$(yq @json statemachine/stock-buyer.asl.yml)"
```

This works, but isn't easily typed out and relies on having a separate application to perform the conversion.

**Additional context**
N/A

**Comment by ChristopheBougere** [comment]
Released in 3.7.0
