### ISSUE TITLE
Fail state is missing CausePath field

### ISSUE THREAD

**Issue by massfords** [ChristopheBougere/asl-validator#147]
**Describe the bug**
The schema for Fail is missing the field "CausePath" field which is a ReferencePath a subset of the IntrinsicFunctions 

**To Reproduce**
clone existing fail test and add both Cause and CausePath. 

**Expected behavior**
Report an error if both properties are defined
report an error if CausePath is not a ReferencePath or one of the intrinsic functions that produces a string

**Version:**
latest

**Additional context**
https://docs.aws.amazon.com/step-functions/latest/dg/amazon-states-language-fail-state.html

**Comment by aninditg98** [comment]
I am experiencing the same issue, seems like `ErrorPath` isn't supported either.

**Comment by ChristopheBougere** [comment]
Fixed by https://github.com/ChristopheBougere/asl-validator/pull/148 and released in 3.8.2

Thanks @massfords
