### ISSUE TITLE
Feature Request: support the new Choice state options

### ISSUE THREAD

**Issue by theburningmonk** [ChristopheBougere/asl-validator#56]
As mentioned in this [issue](https://github.com/serverless-operations/serverless-step-functions/issues/363), the Choice state has added a few more comparison operators such as `IsNull` and `IsPresent`.

https://docs.aws.amazon.com/step-functions/latest/dg/amazon-states-language-choice-state.html

**Comment by ChristopheBougere** [comment]
Thanks for reporting.
There is a bunch of features that have been added last month: https://aws.amazon.com/blogs/aws/aws-step-functions-adds-updates-to-choice-state-global-access-to-context-object-dynamic-timeouts-result-selection-and-intrinsic-functions-to-amazon-states-languages/

If anyone wants to work on this, feel free to submit a PR :)

**Comment by ChristopheBougere** [comment]
Released in 1.8.0, thanks for the PR @theburningmonk 🎉
