### ISSUE TITLE
Validator accepting state machine definition with no terminal state

### ISSUE THREAD

**Issue by vinod-tahelyani** [ChristopheBougere/asl-validator#59]
**Input-**
````Json
{
    "Comment": "A simple minimal example of the States language",
    "StartAt": "Hello World",
    "States": {
        "Hello World": {
            "Type": "Task",
            "Resource": "arn:aws:lambda:us-east-1:123456789012:function:HelloWorld",
            "Next": "Hello World2"
        },
        "Hello World2": {
            "Type": "Task",
            "Resource": "arn:aws:lambda:us-east-1:123456789012:function:HelloWorld",
            "Next": "Hello World3"
        },
        "Hello World3": {
            "Type": "Task",
            "Resource": "arn:aws:lambda:us-east-1:123456789012:function:HelloWorld",
            "Next": "Hello World"
        }
    }
}
````
**Output-**
`✓ State machine definition is valid`

**Comment by ChristopheBougere** [comment]
Sorry for the late answer.
You're right, this package mostly validates the definition syntax in a static way (using JSON schemas).
However, there are already 2 dynamic check: [missing-transition-target](https://github.com/ChristopheBougere/asl-validator/blob/master/src/lib/missing-transition-target.js) and [json-path-errors](https://github.com/ChristopheBougere/asl-validator/blob/master/src/lib/json-path-errors.js).
I think we could implement something similar for ensuring that a terminal state is defined.
Pull request welcome :)
