### ISSUE TITLE
Validator not linting, always shows help

### ISSUE THREAD

**Issue by GaboFDC** [ChristopheBougere/asl-validator#72]
**Describe the bug**
When trying to use the validator, it prints the help.
I'm passing the the --json-path just as always but it prints the help

**To Reproduce**
just try to use it:

```bash
$ asl-validator --json-path states_good_1.json
Usage: asl-validator [options]

Amazon States Language validator

Options:
  -v, --version                       output the version number
  --json-definition <jsonDefinition>  JSON definition
  --json-path <jsonPath>              JSON path
  --silent                            silent mode
  -h, --help                          display help for command
```

```json
any jsonm or file
```

**Expected behavior**
The linter/validator should run

**Version:** [e.g. 1.9.4, can be found by running `asl-validator --version`]
1.9.7

**Additional context**

**Comment by ChristopheBougere** [comment]
Hi @GaboFDC 
Sorry for that, this is due to a commander version upgrade yesterday.
I just rolled it back, could you give a try to 1.9.8?
