### ISSUE TITLE
asl-validator not working on the browser

### ISSUE THREAD

**Issue by alexd-garcia** [ChristopheBougere/asl-validator#77]
**Describe the bug**
I am getting the following error when I try to run the validation on my React application
```
TypeError: _uniq is not a function
    at unique (jsonpath.js:4851:1)
    at Handlers.subscript-descendant-union (jsonpath.js:4711:1)
    at jsonpath.js:5001:1
    at Array.forEach (<anonymous>)
    at jsonpath.js:4998:1
    at Array.forEach (<anonymous>)
    at JSONPath.nodes (jsonpath.js:4992:1)
    at JSONPath.query (jsonpath.js:4958:1)
    at module.exports (json-path-errors.js:3:1)
    at validator (validator.js:40:1)
```

**To Reproduce**
The error comes up with any state machine

```javascript
aslValidator({});
```

**Version:** 2.0.0

**Comment by ChristopheBougere** [comment]
Seems like this is coming from the [jsonpath](https://github.com/dchester/jsonpath) library, which doesn't seem to run in the web:
<img width="299" alt="image" src="https://user-images.githubusercontent.com/1325474/169474584-2c9b5735-107c-4ad6-a5b7-13ee403cc921.png">

If anyone wants to create a PR to switch to another JSON path library, I'd be happy to review it.

**Comment by ChristopheBougere** [comment]
Hi @alexd-garcia 
I just tried [version 2.2.0](https://www.npmjs.com/package/asl-validator/v/2.2.0) in a React/NextJS app and it works like a charm
Thanks to @massfords for switching to another json path library in #87

**Comment by alexd-garcia** [comment]
> Hi @alexd-garcia I just tried [version 2.2.0](https://www.npmjs.com/package/asl-validator/v/2.2.0) in a React/NextJS app and it works like a charm Thanks to @massfords for switching to another json path library in #87

Excellent thanks for the update, I will try that version.
