### ISSUE TITLE
validator rejects path expression containing a hyphen

### ISSUE THREAD

**Issue by massfords** [ChristopheBougere/asl-validator#81]
**Describe the bug**
I'm getting a lexical error parsing an ASL that contains a hyphen in an expression like this: `$.test-input.delay-seconds`

**To Reproduce**
See the AWS example here: https://github.com/aws-samples/aws-stepfunctions-examples/blob/main/sam/app-decompose-for-parallelism/statemachine/runner-simplewait.asl.json

**Expected behavior**
should accept this pattern

**Version:** 
2.0.0

**Additional context**
The ASL cites a specific Java library for its definition of the path expressions. The JS library uses its own BNF grammar for its parser and this grammar doesn't include a hyphen. 

Here's the lib linked to from the spec: https://github.com/json-path/JsonPath (it supports hyphens)

Maybe switch to https://github.com/JSONPath-Plus/JSONPath?

**Comment by massfords** [comment]
Relevant bug from the existing library: https://github.com/dchester/jsonpath/issues/90

The existing library uses `jison` to generate a parser for the expression. The definition for an identifier is what appears to be missing the hyphen.

Here's the existing expression for the lexer to match an identifier: `identifier: "[a-zA-Z_]+[a-zA-Z0-9_]*",`

It could be a quick fix there but maybe there's a better port of the Java library that uses the same lex rules.

**Comment by massfords** [comment]
I was thinking either named rules to be able to explicitly disable as with eslint or something simpler like a level of validation. 

Level 1: schema validation
Level 2: additional rules not enforced by schema
Level 3: path expressions
Level 4: path expressions with schemas defining a Task's input and output shapes

**Comment by massfords** [comment]
switching to jsonpath-plus requires a few tweaks to the existing expressions. I'll get a PR for this once the open PR is merged.

see here: https://github.com/massfords/asl-validator/tree/jsonpathplus

Most of the changes are due to the named parameters on the call like so: 

Before: `jp.query(definition, '$..[\'InputPath\',\'OutputPath\',\'ResultPath\']')`

After: `JSONPath({ json: definition, path: '$..[InputPath,OutputPath,ResultPath]' }`

in the above example, the jsonpath-plus lib doesn't like the quotes around the node identifiers.

**Comment by ChristopheBougere** [comment]
Released in 2.2.0
