### ISSUE TITLE
False positive error with nested parallelism

### ISSUE THREAD

**Issue by thyming** [ChristopheBougere/asl-validator#99]
**Describe the bug**
Certain cases of nested parallelism cause false positive validation errors from this library. 
I've tracked it down to the JSONPath in `nextAndDefaultTargets`, `$.[Next,Default]` for "container" states, not working as I think it's intended to. 

**To Reproduce**
I've added a test case in the associated PR. 

**Expected behavior**
No validation error for the attached test case, which AWS happily accepts. 

**Version:** 
2.2.1

**Comment by ChristopheBougere** [comment]
Released in v 2.2.2

**Comment by ChristopheBougere** [comment]
Also released in v3.0.2
